language: php

php:
  - 5.6
  - 7.1
  - 7.2

addons:
  homebrew:
    taps:
      - exolnet/deprecated
    packages:
      - php
      - php@7.2
      - php@7.1
      - php@5.6
    update: true

before_script:
  - composer global require laravel/valet
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests

cache:
  directories:
    - vendor
